"use client";
import { useMemo,useState } from "react";
import { GitCompareArrows, Sparkles } from "lucide-react";
export default function BeforeAfterClient({items}:{items:any[]}){
 const projects=Array.from(new Set(items.map(x=>x.project)));const [project,setProject]=useState(projects[0]||"");const assets=useMemo(()=>items.filter(x=>x.project===project),[items,project]);const [before,setBefore]=useState(assets[0]?.asset_id||assets[0]?.id||"");const [after,setAfter]=useState(assets[assets.length-1]?.asset_id||assets[assets.length-1]?.id||"");
 const b=assets.find(x=>(x.asset_id||x.id)===before)||assets[0];const a=assets.find(x=>(x.asset_id||x.id)===after)||assets[assets.length-1]||assets[0];
 return <><div className="card section"><div className="formGrid"><label>Project<select className="search" value={project} onChange={e=>{setProject(e.target.value);const next=items.filter(x=>x.project===e.target.value);setBefore(next[0]?.asset_id||next[0]?.id||"");setAfter(next[next.length-1]?.asset_id||next[next.length-1]?.id||"");}}>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label>Before<select className="search" value={before} onChange={e=>setBefore(e.target.value)}>{assets.map(x=><option key={x.asset_id||x.id} value={x.asset_id||x.id}>{x.title} · {x.date}</option>)}</select></label><label>After<select className="search" value={after} onChange={e=>setAfter(e.target.value)}>{assets.map(x=><option key={x.asset_id||x.id} value={x.asset_id||x.id}>{x.title} · {x.date}</option>)}</select></label></div></div>
 <div className="card section"><div className="beforeAfter">{[["BEFORE",b],["AFTER",a]].map(([label,x]:any)=><div className="compare" key={label}><span className="badge">{label} · {x?.date||"—"}</span>{x?<img src={x.src} alt={x.title}/>:<div className="emptyState">No asset</div>}<p className="muted">{x?.title}</p></div>)}</div><div className="section"><div className="sectionHead"><h2>Evidence comparison</h2><span className="badge"><GitCompareArrows size={12}/> {a&&b&&a.asset_id!==b.asset_id?"Selected pair":"Select two different assets"}</span></div><div className="card" style={{marginTop:18,background:"#10261a"}}><div className="eyebrow">AI-ready comparison</div><p style={{lineHeight:1.7}}>Compare the selected source assets side-by-side. Cloudinary preserves the original asset IDs, dates, dimensions, tags and context so an AI comparison service can operate on traceable evidence.</p></div></div></div></>;
}
